### ISSUE TITLE
Extraneous spacing on last child of pipe, crumb, and inlineblock lists

### ISSUE THREAD

**Issue by nategraves** [meetup/sassquatch#320]
Right now, most horizontal lists have a padding-right, margin-right, or both to provide whitespace between list elements. We could reset the last child's spacing to 0 so that the list won't inadvertently cause spacing issues.

**Comment by akdetrick** [comment]
In addition to `:last-child` we also select a `.last` class. That should be good enough for now if we run into the last-child visibility case.

We'll have a bit more room to be clever with `nth-child(odd/even)` selectors in Sassquatch 2
